sudo: required
services: 
    - docker
before_install:
    - docker build -t genavyb1/react-test -f ./client/Dockerfile.dev ./client
scripts:
    - docker run -e CI=true genavyb1/react-test npm test
after_success:
    - docker build -t genavyb1/multi-client ./client
    - docker build -t genavyb1/multi-nginx ./nginx
    - docker build -t genavyb1/multi-server ./server
    - docker build -t genavyb1/multi-worker ./worker

# Log in to the docker CLI
    - echo "$DOCKER_PASSWORD1" | docker login -u "$DOCKER_ID1" --password-stdin
#Take those image and push them to docker hub
    - docker push genavyb1/multi-client
    - docker push genavyb1/multi-nginx 
    - docker push genavyb1/multi-server
    - docker push genavyb1/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-205366435539"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
